spring:
  application:
    name: demo2
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://16.171.252.182:5432/drawing_db
#    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
logging:
  level:
    root: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: demo2.domain
