spring:
  application:
    name: demo2
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://16.171.252.182:5432/drawing_db
#    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
logging:
  level:
    root: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: demo2.domain
security:
  oauth2:
    client:
      registration:
        kakao:
          client-id: "59423bd975fc14e79e8f0314203ed60a"
          redirect-uri: "{baseUrl}/oauth/kakao/callback"
          authorization-grant-type: authorization_code
          scope: "profile_nickname, profile_image"
          client-name: Kakao
      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: id